### ISSUE TITLE
Problem launching CellExplorer

### ISSUE THREAD

**Issue by nnitzan** [petersenpeter/Cell-Explorer#2]
Hi Peter, 
I tried to use the new version of CellExplorer, loading the data and metadata and calculating all metrics including mono_res works fine. However, when launching the CellExplorer viewer I get the following error 
"Identifier 'fig' is not a function or a shared variable. To share 'fig' with nested function, initialize it in the current scope. For more information, see Sharing Variables Between Parent and Nested Functions." 
Could it have something to do with the MATLAB version? I'm using 2019b. 

thanks!

**Comment by petersenpeter** [comment]
Hi Noam
Did you download the most recent version? Does this happens in the pipeline or separately in the Cell Explorer? It could be a Matlab version issue, that I have not experienced, as the never versions of Matlab are more strict with shared variables. I will see if I can reproduce the problem and update the repository.

**Comment by nnitzan** [comment]
it only happens in the CellExplorer, the pipeline runs fine (it creates a session, cell_metrics and mono_res cell infos ). I'm using the most recent version.

thanks!

**Comment by petersenpeter** [comment]
I did a quick fix that should solve it.

**Comment by petersenpeter** [comment]
Let me know how it goes

**Comment by nnitzan** [comment]
wow that was fast, works now! 
thanks!

**Comment by petersenpeter** [comment]
Great. Figure handles in Matlab can be a headache to handle... :-)
