### ISSUE TITLE
Waveforms from bad channels not excluded

### ISSUE THREAD

**Issue by nnitzan** [petersenpeter/Cell-Explorer#4]
Hi Peter, 

I have a bad channel on the probe and labeled it in the session metadata as 'Bad'. 
However, this channel is still used for the waveform extraction and because the large noise amplitude, is selected as the channel with largest waveform amplitude for display in CellExplorer. 
Are there any extra steps to do in order to avoid this during the creation of the sessionInfo or is it a bug? 

best,

Noam 
![session](https://user-images.githubusercontent.com/26693683/79448044-12eb4880-7fe1-11ea-88ab-cfe25624e4ef.jpg)
![noisechannel](https://user-images.githubusercontent.com/26693683/79448046-1383df00-7fe1-11ea-98cf-1114e2b2a9b3.jpg)

**Comment by petersenpeter** [comment]
Hi Noam. 

Thanks for reaching out with your issue(s). It seems it was a bug, as the session struct was not provided for the waveform extraction. I just updated the repo and the issue should be fixed. 

You can delete your .spikes file and forceReload the waveforms in ProcessCellMetrics (or just delete the cell_metrics file as well, and run the ProcessCellMetrics again).

What are your monitor's resolution and size? I keep seeing that the UI is not behaving as it should on your screenshots.

- Peter

**Comment by nnitzan** [comment]
Hi Peter,

Thanks the issue seems to be fixed now, as judged by the summary figures, but after updating the repository I get the following error message

Reference to non-existent field 'plotInsetChannelMap'.

Error in CellExplorer (line 410)
if UI.settings.plotInsetChannelMap; UI.menu.display.showChannelMap.ops(UI.settings.plotInsetChannelMap).Checked = 'on'; end

Error in ProcessCellMetrics (line 1316)
CellExplorer('metrics',cell_metrics,'summaryFigures',true,'plotCellIDs',-1); % Creates group plots only

-Noam
________________________________

**Comment by petersenpeter** [comment]
I forgot to push the preference file to Github. Could you update your repo and try again?

**Comment by nnitzan** [comment]
Thanks! it's working well now

________________________________

**Comment by petersenpeter** [comment]
Great. I forgot that I changed filenames and some of the folder structure so I hope it did not cause any further problems for you. The UI should be more responsive after your update.

**Comment by nnitzan** [comment]
Thanks Peter,

Fyi - I noticed another minor bug in ProcessCellMetrics (line 1316) when plotting the connectivity graph in the summary plots if there aren't any connections detected during in the MonoSyn the function crashes and cell_metrics is not extracted

best,

Noam

Noam Nitzan
Schmitz Lab
Charité University Medicine Berlin
Charité Crossover NWFZ, Campus Mitte
Virchowweg 6 - Charitéplatz 1
10117 Berlin, Germany

Phone: +49-30-450-639-063
http://schmitz.neurocure.de
_______________________________
________________________________

**Comment by petersenpeter** [comment]
Thanks Noam. I will fix it today.
